"""CPU power-diagram utilities for SDF-guided mesh extraction.

PowerFoam parameterizes the scene as a bounded power diagram: each cell is
generated by a site p_i and a radius r_i (weight w_i = r_i^2).  During
training only the Čech complex of the bounding spheres is needed, so the
full diagram is never built.  For mesh extraction, however, we want the
actual cell polyhedra so we can port SDFoam's extraction strategy (select
cells whose SDF is near zero and emit their faces).

The power diagram is computed exactly via the classic lifting construction:
lift each site to 4D as (x, y, z, |p|^2 - w).  The facets of the lower
convex hull of the lifted points are the tetrahedra of the regular
triangulation, whose dual is the power diagram.  The vertex of the power
diagram dual to a tetrahedron is its radical center (the point with equal
power distance to all four sites).

Everything here runs on CPU with numpy/scipy and is independent of the
renderer, so it can be unit-tested without a GPU.
"""

import itertools

import numpy as np
from scipy.spatial import ConvexHull


def regular_triangulation(points: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """Regular (weighted Delaunay) triangulation via the 4D lifting trick.

    Parameters
    ----------
    points : (N, 3) float array of sites
    weights : (N,) float array of power weights (radius squared)

    Returns
    -------
    (M, 4) int array of site indices forming the tetrahedra.  Sites whose
    power cell is empty (redundant sites) appear in no tetrahedron.
    """
    points = np.asarray(points, dtype=np.float64)
    weights = np.asarray(weights, dtype=np.float64)

    lift = (points**2).sum(axis=1) - weights
    lifted = np.concatenate([points, lift[:, None]], axis=1)

    hull = ConvexHull(lifted, qhull_options="Qt")

    # Keep lower-hull facets: outward normal points down in the lifted
    # coordinate.  Those facets project to the regular triangulation.
    lower = hull.equations[:, 3] < -1e-12
    tets = hull.simplices[lower]
    return tets.astype(np.int64)


def power_centers(
    points: np.ndarray, weights: np.ndarray, tets: np.ndarray
) -> np.ndarray:
    """Radical centers of the tetrahedra (= power-diagram vertices).

    The radical center c of sites (a, b, c, d) satisfies
    |c - p_i|^2 - w_i = const, which reduces to the linear system
    2 (p_j - p_0) . c = (|p_j|^2 - w_j) - (|p_0|^2 - w_0), j = 1..3.
    """
    points = np.asarray(points, dtype=np.float64)
    weights = np.asarray(weights, dtype=np.float64)

    p = points[tets]  # (M, 4, 3)
    lift = (points**2).sum(axis=1) - weights  # |p|^2 - w
    f = lift[tets]  # (M, 4)

    A = 2.0 * (p[:, 1:, :] - p[:, :1, :])  # (M, 3, 3)
    b = f[:, 1:] - f[:, :1]  # (M, 3)

    # Solve batched 3x3 systems; guard degenerate (flat) tets.
    centers = np.full((tets.shape[0], 3), np.nan)
    dets = np.linalg.det(A)
    good = np.abs(dets) > 1e-14
    if good.any():
        centers[good] = np.linalg.solve(A[good], b[good][..., None])[..., 0]
    return centers


def cell_vertex_map(tets: np.ndarray, num_sites: int):
    """For each site, the indices of the tetrahedra incident to it.

    Returns a (offsets, indices) CSR-style pair: the tetrahedra of site i
    are ``indices[offsets[i]:offsets[i + 1]]``.
    """
    flat_sites = tets.reshape(-1)
    tet_ids = np.repeat(np.arange(tets.shape[0]), 4)

    order = np.argsort(flat_sites, kind="stable")
    flat_sites = flat_sites[order]
    tet_ids = tet_ids[order]

    counts = np.bincount(flat_sites, minlength=num_sites)
    offsets = np.zeros(num_sites + 1, dtype=np.int64)
    np.cumsum(counts, out=offsets[1:])
    return offsets, tet_ids


def bounding_sites(points: np.ndarray, pad_ratio: float = 0.25):
    """Eight far-away corner sites (zero weight) that bound all real cells."""
    pmin = points.min(axis=0)
    pmax = points.max(axis=0)
    pad = pad_ratio * float(np.linalg.norm(pmax - pmin) + 1e-9)
    lo = pmin - pad
    hi = pmax + pad
    corners = np.array(
        list(itertools.product([lo[0], hi[0]], [lo[1], hi[1]], [lo[2], hi[2]])),
        dtype=np.float64,
    )
    return corners


class PowerDiagram:
    """Precomputed power diagram supporting repeated cell extraction.

    Building the regular triangulation is the expensive step; this class
    computes it once so interactive tools (gui.py) can re-extract different
    cell selections cheaply.
    """

    def __init__(self, points: np.ndarray, weights: np.ndarray, pad_ratio=0.25):
        points = np.asarray(points, dtype=np.float64)
        weights = np.asarray(weights, dtype=np.float64)
        self.num_real = points.shape[0]

        corners = bounding_sites(points, pad_ratio)
        all_points = np.vstack([points, corners])
        all_weights = np.concatenate([weights, np.zeros(len(corners))])

        tets = regular_triangulation(all_points, all_weights)
        self.centers = power_centers(all_points, all_weights, tets)
        self.offsets, self.tet_ids = cell_vertex_map(tets, all_points.shape[0])

    def cell_polyhedra(self, selected, verbose: bool = True):
        """Convex polyhedra of the selected cells as one triangle soup.

        Returns
        -------
        verts : (V, 3) float array
        faces : (F, 3) int array
        face_cell : (F,) int array mapping each triangle to its source cell
        """
        all_verts = []
        all_faces = []
        face_cell = []
        vertex_offset = 0

        iterator = selected
        if verbose:
            try:
                from tqdm import tqdm

                iterator = tqdm(selected, desc="Building power-cell mesh")
            except ImportError:
                pass

        for cell_idx in iterator:
            cell_idx = int(cell_idx)
            if cell_idx >= self.num_real:
                continue
            incident = self.tet_ids[
                self.offsets[cell_idx] : self.offsets[cell_idx + 1]
            ]
            cell_verts = self.centers[incident]
            cell_verts = cell_verts[np.isfinite(cell_verts).all(axis=1)]
            if cell_verts.shape[0] < 4:
                continue
            try:
                hull = ConvexHull(cell_verts, qhull_options="Qt QJ")
            except Exception:
                continue

            all_verts.append(cell_verts)
            all_faces.append(hull.simplices + vertex_offset)
            face_cell.extend([cell_idx] * hull.simplices.shape[0])
            vertex_offset += cell_verts.shape[0]

        if not all_verts:
            return (
                np.zeros((0, 3)),
                np.zeros((0, 3), dtype=np.int64),
                np.zeros((0,), dtype=np.int64),
            )

        return (
            np.vstack(all_verts),
            np.vstack(all_faces).astype(np.int64),
            np.asarray(face_cell, dtype=np.int64),
        )


def extract_cell_meshes(
    points: np.ndarray,
    weights: np.ndarray,
    selected: np.ndarray,
    pad_ratio: float = 0.25,
    verbose: bool = True,
):
    """One-shot convenience wrapper around :class:`PowerDiagram`.

    Parameters
    ----------
    points : (N, 3) sites
    weights : (N,) power weights (radius squared)
    selected : (K,) indices of cells to extract
    pad_ratio : bounding-corner padding relative to the scene diagonal
    """
    diagram = PowerDiagram(points, weights, pad_ratio)
    return diagram.cell_polyhedra(selected, verbose=verbose)
